title: 何贤君的Blog
description: 这是我的个人博客
url: "https://yihngwan.github.io"
baseurl: ""
author:
  name: "何贤君"
  email: "yihngwan@outlook.com"
timezone: "Asia/Shanghai"
locale: "zh-CN"
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/
paginate: 5
theme: jekyll-theme-minimal
# Navigation links for the blog
nav_links:
  - title: "home"
    url: "https://yihngwan.github.io/"
  - title: "新的页面"
    url: "/pages/new_page"
  - title: "test"
    url: "test.html"
  - title: "About"
    url: "/pages/about"
  - title: "旧的作品"
    url: "https://yihngwan.github.io/study_html/"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
