theme: jekyll-theme-minimal
title: 何贤君的githubBlog
# Navigation links for the blog
# Each link should have a title and a URL
nav_links:
  - title: "home"
    url: "https://yihngwan.github.io/"
  - title: "新的页面"
    url: "/pages/new_page"
  - title: "test"
    url: "test.html"
  - title: "About"
    url: "/pages/about"
  - title: "旧的作品"
    url: "https://yihngwan.github.io/study_html/"

