theme: jekyll-theme-minimal
title: 何贤君的githubBlog
nav_links:
  - title: "新的页面"
    url: "/pages/new_page"
  - title: "About"
    url: "/pages/about.md"
    - title: "旧的作品"
    url: "https://yihngwan.github.io/study_html/"